layout_options.settings:
  type: config_object
  label: 'Layout Options settings'
  mapping:
    layout_overrides:
      type: sequence
      label: 'The overridden layouts'
      sequence:
        type: boolean
