<?php

/**
 * @file
 * Hook implementations for the UI Skins module.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\ui_skins\HookHandler\FormSystemThemeSettingsAlter;
use Drupal\ui_skins\HookHandler\PageTop;
use Drupal\ui_skins\HookHandler\PreprocessHtml;
use Drupal\ui_skins\UiSkinsInterface;

/**
 * Implements hook_form_FORM_ID_alter() for 'system_theme_settings'.
 */
function ui_skins_form_system_theme_settings_alter(array &$form, FormStateInterface $form_state): void {
  /** @var \Drupal\ui_skins\HookHandler\FormSystemThemeSettingsAlter $instance */
  $instance = \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(FormSystemThemeSettingsAlter::class);
  $instance->alter($form, $form_state);
}

/**
 * Implements hook_page_top().
 */
function ui_skins_page_top(array &$page_top): void {
  /** @var \Drupal\ui_skins\HookHandler\PageTop $instance */
  $instance = \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(PageTop::class);
  $instance->alter($page_top);
}

/**
 * Implements hook_config_schema_info_alter().
 */
function ui_skins_config_schema_info_alter(array &$definitions): void {
  if (!isset($definitions['theme_settings']['mapping'])) {
    return;
  }

  $definitions['theme_settings']['mapping'][UiSkinsInterface::CSS_VARIABLES_THEME_SETTING_KEY] = [
    'type' => 'ui_skins.css_variables',
  ];
  $definitions['theme_settings']['mapping'][UiSkinsInterface::THEME_THEME_SETTING_KEY] = [
    'type' => 'ui_skins.theme',
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function ui_skins_preprocess_html(array &$variables): void {
  /** @var \Drupal\ui_skins\HookHandler\PreprocessHtml $instance */
  $instance = \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(PreprocessHtml::class);
  $instance->preprocess($variables);
}
