<?php

/**
 * @file
 * Contains libraries_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function libraries_ui_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.libraries_ui') {
    $text = file_get_contents(__DIR__ . '/README.md');
    if (!Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
      $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
      $parser = $parser_manager->getDefaultParser([
        'render_strategy' => ['type' => 'none'],
      ]);
      return $parser->parse($text);
    }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function libraries_ui_theme() {
  return [
    'libraries_ui' => [
      'variables' => [
        'libraries' => NULL,
      ],
    ],
  ];
}
