name: UI Patterns Settings
type: module
description: Configure patterns with settings
package: User interface
core_version_requirement: ^8 || ^9 || ^10
dependencies:
  - ui_patterns:ui_patterns
  - token:token

# Information added by Drupal.org packaging script on 2023-10-27
version: '8.x-2.1'
project: 'ui_patterns_settings'
datestamp: 1698415708
